### ISSUE TITLE
BUG: Pytask checks for dependencies when using the `skip` decorator

### ISSUE THREAD

**Issue by roecla** [pytask-dev/pytask#104]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pytask. (0.0.14)
- [x] (optional) I have confirmed this bug exists on the `main` branch of pytask.

#### Code Sample, a copy-pastable example

```python
import pytask

@pytask.mark.skip
@pytask.mark.depends_on("missing.txt")
@pytask.mark.produces("product.txt")
def task_that_should_be_skipped(depends_on, produces):
    pass

```

```python-traceback

─────────────────────────────── Start pytask session ────────────────────────────────
Platform: linux -- Python 3.8.10, pytask 0.0.14, pluggy 0.13.1
Root: /home/klara/Dropbox/Downloads/pytask_mwe
Collected 1 task.

────────────────────── Failures during resolving dependencies ───────────────────────

ResolvingDependenciesError: Some dependencies do not exist or are not produced by any
task. See the following tree which shows which dependencies are missing for which 
tasks.

Missing dependencies:                                                                
└── 📄 pytask_mwe/missing.txt                                                        
    └── 📝 pytask_mwe/task_skip_with_dependencies.py::task_that_should_be_skipped    

─────────────────────────────────────────────────────────────────────────────────────
```

#### Problem description

Often the reason we want to skip a task is because we are currently not producing the necessary input and don't want pytask to raise an error. Therefore, when a task is marked to be skipped it shouldn't matter whether its dependencies are in the DAG or not. 

#### Expected Output

The task should run through without an error.

**Comment by tobiasraabe** [comment]
Thanks for the report! I'll have a look at the issue soon.
