### ISSUE TITLE
BUG: Latest pytask does not abort when Keyboard Interrupt is done during 

### ISSUE THREAD

**Issue by roecla** [pytask-dev/pytask#114]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pytask: 0.0.16

- [ ] (optional) I have confirmed this bug exists on the `main` branch of pytask.

#### Code Sample, a copy-pastable example

```python
import pytask

breakpoint()


def task_example_task():
    pass

```

#### Problem description

When I set a python breakpoint outside a task function (e.g. to inspect a parametrization) and try to run pytask (no matter whether with or without the `--pdb` flag) it just hangs in the task collection and does not even respond to Keyboard Interrupts. I have found no other way to get out of the situation than closing the terminal in which I tried to ran pytask and kill the process.

**Note:** I am using pdb++. I have not tried what the behavior would be with old school pdb.

#### Expected Output

With a breakpoint outside the task functions, I would have expected pytask to **either** also enter pdb normally (old behavior) **or** to abort and throw an Error that it has to be run with the `--pdb` flag. With the `--pdb` flag I would have definitiely expected pytask to normally enter pdb at the breakpoint.

#### Screenshot

![image](https://user-images.githubusercontent.com/9567321/123411507-d1750680-d5b0-11eb-9a87-3a322669af78.png)

#### Earlier versions of pytask

0.0.14: breakpoint outside of task functions work both with and without `--pdb` flag
0.0.15: pytask does not exit when there's a breakpoint outside the task function, irrespective of whether the `--pdb` flag is set
0.0.16: pytask does not exit when there's a breakpoint outside the task function, irrespective of whether the `--pdb` flag is set

**Comment by tobiasraabe** [comment]
I forgot to test the interaction of the live status and the debugger manually since some details are not captured by the test suite. #106 implements a debugger-friendly version of a live table showing the progress of the execution. It will be extended to also fix the status during collection.
