### ISSUE TITLE
ENH: Enhance the suggestions made by `pytask clean`.

### ISSUE THREAD

**Issue by tobiasraabe** [pytask-dev/pytask#146]
#### Describe the solution you'd like

- Add an option to ignore files which are known by git.
- Differentiate between folder to collect from and folder to delete from.

**Comment by axtimhaus** [comment]
An option in the config file for ignoring files would also be helpful. The current `ignore` option does not work with `clean`.

**Comment by tobiasraabe** [comment]
Thanks for the reprot. I guess the following lines are part of the problem.

https://github.com/pytask-dev/pytask/blob/2bbb8e7dc788eec36838c44ee0479fb0f3b2751b/src/_pytask/clean.py#L53-L56

**Comment by tobiasraabe** [comment]
How to get all files tracked by git.

```python
def zsplit(s: str) -> list[str]:
    s = s.strip('\0')
    if s:
        return s.split('\0')
    else:
        return []

def get_all_files() -> list[str]:
    return zsplit(cmd_output('git', 'ls-files', '-z')[1])


zsplit(get_all_files())
```
