### ISSUE TITLE
DOC: General overhaul

### ISSUE THREAD

**Issue by hmgaudecker** [pytask-dev/pytask#214]
### Landing page improvements

- Do not expect users to know about pytest
- Add getting started 
  1. installation
  2. toy project / screencasts
  3. point to templates
  4. outline of docs

### Tutorials

- Topics need to be clearer for beginners and follow their "journey" (e.g., invocations should come at no. 2-4, not almost last)

- More explanation on packaging? Why? What are the different components doing? etc.

### How to

Order should be something like

1. Organization *drop altogether? title doesn't make me want to look there or know what to expect, content seems more on contribution to docs?)*
1. Structure of a research project
1. Structure of task files
1. Templates and projects *why in how-to guides?*
1. How to influence the build order
1. How to write a plugin

In any case, how to write a plugin should go last, not first.

### Explanations

- Improve comparison to other tools as discussed via Zoom (when do I want to use pytask? when do I not want to use it?)
  - Use snakemake paper for it: https://f1000research.com/articles/10-33/v2
- I am not sure about the title / scope of "Explanations". 

### General structure

- Add plugin documentation, all should be in one place. Users see this as one project.
- Maybe set up a dedicated repo?

**Comment by tobiasraabe** [comment]
I am closing this since many of the issues have been addressed.
