### ISSUE TITLE
QST: Bug in the docs?

### ISSUE THREAD

**Issue by augustebaum** [pytask-dev/pytask#317]
#### Question about pytask
The example in <https://pytask-dev.readthedocs.io/en/stable/tutorials/defining_dependencies_products.html#nested-dependencies-and-products> might contain a bug:
```python
@pytask.mark.depends_on(
    {
        "model": [SRC / "models" / "model.py"],
        "data": {"a": SRC / "data" / "a.pkl", "b": SRC / "data" / "b.pkl"},
    }
)
@pytask.mark.produces(BLD / "models" / "fitted_model.pkl")
def task_fit_model():
    ...
```
Shouldn't `task_fit_model` take `depends_on` and `produces` as fixtures?

Thanks for your attention!

**Comment by tobiasraabe** [comment]
Hi @augustebaum, yes, you are right! The example is clearer if the function also accepts both arguments. The next line

> depends_on within the function will be

also implies that it is an argument.

Thanks again for reading so carefully!
