### ISSUE TITLE
QST: Creating a task programmatically from a name

### ISSUE THREAD

**Issue by augustebaum** [pytask-dev/pytask#324]
#### Question about pytask

Hi, I was wondering if it would be possible to define a task programmatically,
e.g. based on a name. I made the MWE below; I thought this would result in
the collection of 3 tasks, but actually none are collected.

Would you mind explaining why this is the case?

Thanks very much in advance! :)

```python
import pytask

for i in range(3):

    definition = f"""
@pytask.mark.task(id=i)
def task_test_{i}():
   print('hello')
"""
    exec(definition)

```

**Comment by tobiasraabe** [comment]
Hi! I expected your example to work. The problem is that the `__code__` attribute of dynamically created functions has its path set to CWD + `<script>`. For normal functions it is the path to the module. This prevented pytask from collecting the function.

I pushed some changes in #325 to make it work, but I need to review it more carefully. You can test the changes if you want.

**Comment by augustebaum** [comment]
Thanks for the once again super quick response. How would I go testing the changes? If I've missed this information in the docs I apologize in advance ^^'

**Comment by tobiasraabe** [comment]
It does not exist. No worries :D. I should add it. The following should work.

```console
pip install --no-deps https://github.com/pytask-dev/pytask@fix-pytask-mark-task-for-dynamically-created-functions
```

**Comment by augustebaum** [comment]
It worked on my MWE, but I'm hesitant to update `pytask` in my real codebase until the PR has been reviewed. Looking forward to seeing this in an upcoming release!

Quick note: the command to install gave me a 404. I believe unless certain config options are set the command should be
```
pip install --no-deps git+https://github.com/pytask-dev/pytask@fix-pytask-mark-task-for-dynamically-created-functions
```
(note the `git+`).

Thanks again!

**Comment by tobiasraabe** [comment]
Thanks for the correction!

I wanted to create a new release soon anyways. Hopefully, I'll find some time to complete it soon.
