### ISSUE TITLE
DOC: Terminal animations seem broken

### ISSUE THREAD

**Issue by augustebaum** [pytask-dev/pytask#327]
#### Location of the documentation

See for example [here](https://pytask-dev.readthedocs.io/en/stable/how_to_guides/capture_warnings.html?highlight=capture).

#### Suggested fix for documentation

Maybe adding an extra column in the terminal window is possible?

**Comment by tobiasraabe** [comment]
Can you post a screenshot of what you are seeing? For me, it looks fine on the desktop, but on mobile, it is also broken for me.

**Comment by augustebaum** [comment]
Here you go! Should have done this sooner ^^'

<img width="1187" alt="Screenshot 2022-12-20 at 11 23 01" src="https://user-images.githubusercontent.com/52001167/208644235-68bc19d6-402d-4312-ac27-1b086980c5f6.png">

**Comment by tobiasraabe** [comment]
I created all animations with 78 characters in width, which is probably too much for some displays. The animations for typer are around 53 characters, and even there, it breaks on mobile. I could reduce the animations by a couple of characters or maybe even decrease the width of the whole container.

Thanks for reporting the issue 🙏! I will see what I can do over the holidays.
