### ISSUE TITLE
BUG: module.__name__ not set set correctly during exec in test collection

### ISSUE THREAD

**Issue by NickCrews** [pytask-dev/pytask#374]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pytask.
- [x] (optional) I have confirmed this bug exists on the `main` branch of pytask.

---

#### Problem description

First of all, thanks for this library! A lot of great stuff in here.

See #373 for a PR that adds a failing test.

While I'm not sure what the root cause is / who's fault it is, the actual method of failure is something like this:
Say I have a file `task_a.py`. In https://github.com/pytask-dev/pytask/blob/9b2d93ee103761e85ef77aa606d1d775fcb19b6b/src/_pytask/collect.py#L108-L120, the module spec is created with a module name of `path.stem`, so in my case it is `task_a`. But then IFF you have used a `from __future__ import annotations`, then you go down this code path where dataclasses tries to call ` sys.modules.get("task_a")`, and "task_a" is not importable by itself.

I think we need to be setting the module.__name__ to something else, so it actually is findable within sys.modules, or import/exec it slightly differently?

**Comment by tobiasraabe** [comment]
Hi @NickCrews, thanks for the kind words, and thank you for the bug report + test 🙇.

This seems tricky. I hopefully have some time over the weekend to look into this. My current guess is that the import mechanism is not doing enough, and maybe it needs some of the `sys.path` modification magic pytest is doing. Here for future investigations:

- [`import_path`](https://github.com/pytest-dev/pytest/blob/07eeeb8dfc82de289565a57880ca08b0eac4462d/src/_pytest/pathlib.py#L485)
- [How `import_path` is used](https://github.com/pytest-dev/pytest/blob/07eeeb8dfc82de289565a57880ca08b0eac4462d/src/_pytest/python.py#L617)

**Comment by NickCrews** [comment]
That looks like it would fix the problem, but I'm not sure which `importmode` should be used. [pytests docs on the subject](https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html)
