### ISSUE TITLE
ENH: Add a --maxfail and -x option.

### ISSUE THREAD

**Issue by tobiasraabe** [pytask-dev/pytask#44]
#### Is your feature request related to a problem?

Sometimes you want to have an early exit if one or multiple tasks fail.

#### Describe the solution you'd like

Implement ``--maxfail`` and ``-x``.

**Comment by roecla** [comment]
I think `-x` as an option would be handy but it would actually be enough to show the collected `stdout` in the terminal when the user aborts pytask with `Ctrl+C`. At the moment, that only shows "Aborted!"
