### ISSUE TITLE
DOC:  Code examples in documentation on "Capture warnings" produces errors locally  

### ISSUE THREAD

**Issue by timmens** [pytask-dev/pytask#583]
#### Location of the documentation

https://pytask-dev.readthedocs.io/en/v0.4.7/how_to_guides/capture_warnings.html

#### Documentation problem

The documentation states:

```python
...

@pytask.mark.filterwarnings("ignore:.*:SettingWithCopyWarning")

...
```

which results in the following output `AttributeError: module 'builtins' has no attribute 'SettingWithCopyWarning'`, when running `pytask` on the corresponding task file (`pytask == 0.4.7` and `pandas==2.2.1`).

#### Suggested fix for documentation

To make the example code run, the decorator argument should be changed to:

```python
...

@pytask.mark.filterwarnings("ignore:.*:pandas.errors.SettingWithCopyWarning")

...
```

Additionally, it could be nice to have one or two sentences on how to deal with custom warnings, or warnings that are imported from other packages, and how to ignore them in the `pyproject.toml`.

**Comment by tobiasraabe** [comment]
Thanks a lot, @timmens! Yes, this should be corrected.
