### ISSUE TITLE
BUG: Type Annotations in `PythonNode` Wrong

### ISSUE THREAD

**Issue by axtimhaus** [pytask-dev/pytask#654]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pytask.
- [x] (optional) I have confirmed this bug exists on the `main` branch of pytask.

---

#### Code Sample, a copy-pastable example

This is the example from the docs https://pytask-dev.readthedocs.io/en/stable/how_to_guides/hashing_inputs_of_tasks.html.

```python
import json
from pathlib import Path
from typing import Annotated
from typing import Any

from deepdiff import DeepHash
from pytask import Product
from pytask import PythonNode


def calculate_hash(x: Any) -> str:
    return DeepHash(x)[x]


node = PythonNode(value={"a": 1, "b": 2}, hash=calculate_hash)


def task_example(
    data: Annotated[dict[str, int], node],
    path: Annotated[Path, Product] = Path("file.txt"),
) -> None:
    path.write_text(json.dumps(data))
```

#### Problem description

When I do this example, my type checker complains about the type of the provided hash function.

Type annotation from current master:

https://github.com/pytask-dev/pytask/blob/f18df8f7de1cc941f0b93bca5fa6b7575a29e61a/src/_pytask/nodes.py#L238

I think `bool` as return type of the callable makes no sense here.
Running the code works perfectly fine, just the checker complaining.

#### Expected Output

By looking into the source `Callable[[Any], Any]` would work (because the result is passed to `str()`), or a more defined one like `Callable[[Any], int | str | bytes]` as these are common returns of hash functions.

**Comment by tobiasraabe** [comment]
Thanks for filing the issue, @axtimhaus! Looks good. I will have a look soon. I am wondering whether we need the flexibility with the union return type. Maybe I find packages offering similar functionality.

**Comment by tobiasraabe** [comment]
I decided for the union return type `int | str` because it is what the interface currently supports out of the box and what the internal hashing function returns. In case there is demand for other returns, let's consider them when requested.

**Comment by axtimhaus** [comment]
Seems reasonable. Thank you for the quick response and fix!
